
name: Deploy using published action

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false
  
  


jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    environment:
      name: demo
      url: ${{ steps.deploy_to_pages.outputs.github_pages_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node env
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Vite Github Pages Deployer
        uses: skywarth/vite-github-pages-deployer@master
        #with:
          #install_phase_node_env: 'production'
          #build_phase_node_env: 'dev'
          #debug_mode: 'true'
        id: deploy_to_pages
      - name: dump outputs
        run:  echo "${{steps.deploy_to_pages.outputs.github_pages_url}}"


      
      
